imports:
  - https://raw.githubusercontent.com/aspnet/Benchmarks/master/src/BombardierClient/bombardier.yml

jobs:
  netty:
    source:
      Repository: https://github.com/davidfowl/netty-playground
      BranchOrCommit: master
      DockerFile: Dockerfile
      DockerImageName: netty
    port: 8080

scenarios:
  json:
    application:
      job: netty
    warmup:
      job: bombardier
        variables:
          serverPort: 8080
    load:
      job: bombardier
        variables:
          serverPort: 8080
          path: /json